### PR TITLE
Fix escape html symbols in textarea and fix work with empty textarea

### LINKED ISSUE #17: Miss highlight if there are some HTML tags
look at https://codepen.io/exzant/pen/NvLJzm

### PR DESCRIPTION
**Pull request by nicolaichuk**
@lonekorean, please review and merge with upstream.

fix #17

### CODE REVIEW

**Comment by nicolaichuk** [comment]
fix https://github.com/lonekorean/highlight-within-textarea/issues/17

**Comment by lonekorean** [comment]
Hi Victor, really appreciate the PR, but sad to say it might not be needed. I'm currently rewriting the `renderMarks` function to fix a couple issues (including this one) and I don't think this code will be compatible.

I am curious about your "fix newline" commit though, was that a pre-existing bug? If so, can you tell me how it happens?

**Comment by nicolaichuk** [comment]
@lonekorean

> I'm currently rewriting the renderMarks function to fix a couple issues...

When will you plane to release new version of "highlight-within-textarea"?

> If so, can you tell me how it happens?

need be replaced ```\r\n``` to ```\n``` in input variable

and need be replaced ```\n``` in textarea to ```<br/>``` in div html

otherwise the position after newlines for highlight does not match with what returns [selectionStart of textarea](https://stackoverflow.com/questions/7745867/how-do-you-get-the-cursor-position-in-a-textarea).

**Comment by lonekorean** [comment]
Just published v2.0.4.

**Pull request closed without merging**
